
name: AutoDoc
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run:
    permissions:
      contents: write
    uses: Drag-GameStudio/ADG/.github/workflows/reuseble_agd.yml@main
    secrets:
      ADG_API_TOKEN: ${{ secrets.ADG_API_TOKEN }}
